# OPT ?= 2
TRI_LAYER_ENABLE = no
ENCODER_MAP_ENABLE = yes
VIA_ENABLE = no
TAP_DANCE_ENABLE=yes
LTO_ENABLE = yes
EXTRAFLAGS += -flto=auto
LEADER_ENABLE = yes
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
LAYER_LOCK_ENABLE = yes
NKRO_ENABLE = no
MOUSEKEY_ENABLE = no
MIDI_ENABLE = no
OS_DETECTION_ENABLE = no
RAW_ENABLE = no
OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=9
# BOOTMAGIC_ENABLE = lite
# BACKLIGHT_ENABLE = no
# LED_MATRIX_ENABLE = yes
# LED_MATRIX_DRIVER = snled27351
# RGB_MATRIX_DRIVER = is31fl3218
# RGBLIGHT_ENABLE = yes